name: ${name}
version: ${version}
main: ${groupId}.${artifactId}.${name}Plugin
author: ${author}
commands:
    survivalgames:
        description: Base command
        usage: /<command> [args]
        aliases: [sg]
permissions:
    survivalgames.command:
        description: Base permission
        default: true
    survivalgames.create:
        description: Allows /sg create
        default: op
    survivalgames.delete:
        description: Allows /sg delete
        default: op
    survivalgames.list:
        description: Allows /sg list
        default: true
    survivalgames.join:
        description: Allows /sg join
        default: true
    survivalgames.leave:
        description: Allows /sg leave
        default: true
    survivalgames.addspawn:
        description: Allows /sg addspawn
        default: op
    survivalgames.info:
        description: Allows /sg info
        default: true
    survivalgames.start:
        description: Allows /sg start
        default: op
    survivalgames.stop:
        description: Allows /sg stop
        default: op
    survivalgames.teleport:
        description: Allows /sg tp
        default: op
    survivalgames.help:
        description: Allows /sg help
        default: true
    survivalgames.setspawn:
        description: Allows /sg setspawn
        default: op
    survivalgames.setlobbyspawn:
        description: Allows /sg setlobbyspawn
        default: op